export const countryCode_data = [
    { id: "AF", country: "Afghanistan", code: "93" },
    { id: "AL", country: "Albania", code: "355" },
    { id: "DZ", country: "Algeria", code: "213" },
    { id: "AS", country: "American Samoa", code: "1-684" },
    { id: "AD", country: "Andorra", code: "376" },
    { id: "AO", country: "Angola", code: "244" },
    { id: "AI", country: "Anguilla", code: "1-264" },
    { id: "AQ", country: "Antarctica", code: "672" },
    { id: "AG", country: "Antigua and Barbuda", code: "1-268" },
    { id: "AR", country: "Argentina", code: "54" },
    { id: "AM", country: "Armenia", code: "374" },
    { id: "AW", country: "Aruba", code: "297" },
    { id: "AU", country: "Australia", code: "61" },
    { id: "AT", country: "Austria", code: "43" },
    { id: "AZ", country: "Azerbaijan", code: "994" },
    { id: "BS", country: "Bahamas", code: "1-242" },
    { id: "BH", country: "Bahrain", code: "973" },
    { id: "BD", country: "Bangladesh", code: "880" },
    { id: "BB", country: "Barbados", code: "1-246" },
    { id: "BY", country: "Belarus", code: "375" },
    { id: "BE", country: "Belgium", code: "32" },
    { id: "BZ", country: "Belize", code: "501" },
    { id: "BJ", country: "Benin", code: "229" },
    { id: "BM", country: "Bermuda", code: "1-441" },
    { id: "BT", country: "Bhutan", code: "975" },
    { id: "BO", country: "Bolivia", code: "591" },
    { id: "BA", country: "Bosnia and Herzegovina", code: "387" },
    { id: "BW", country: "Botswana", code: "267" },
    { id: "BV", country: "Bouvet Island", code: "47" },
    { id: "BR", country: "Brazil", code: "55" },
    { id: "IO", country: "British Indian Ocean Territory", code: "246" },
    { id: "BN", country: "Brunei Darussalam", code: "673" },
    { id: "BG", country: "Bulgaria", code: "359" },
    { id: "BF", country: "Burkina Faso", code: "226" },
    { id: "BI", country: "Burundi", code: "257" },
    { id: "KH", country: "Cambodia", code: "855" },
    { id: "CM", country: "Cameroon", code: "237" },
    { id: "CA", country: "Canada", code: "1" },
    { id: "CV", country: "Cape Verde", code: "238" },
    { id: "KY", country: "Cayman Islands", code: "1-345" },
    { id: "CF", country: "Central African Republic", code: "236" },
    { id: "TD", country: "Chad", code: "235" },
    { id: "CL", country: "Chile", code: "56" },
    { id: "CN", country: "China", code: "86" },
    { id: "CX", country: "Christmas Island", code: "61" },
    { id: "CC", country: "Cocos (Keeling) Islands", code: "61" },
    { id: "CO", country: "Colombia", code: "57" },
    { id: "KM", country: "Comoros", code: "269" },
    { id: "CG", country: "Congo", code: "242" },
    { id: "CD", country: "Congo, Democratic Republic of the", code: "243" },
    { id: "CK", country: "Cook Islands", code: "682" },
    { id: "CR", country: "Costa Rica", code: "506" },
    { id: "CI", country: "Cote D'Ivoire", code: "225" },
    { id: "HR", country: "Croatia", code: "385" },
    { id: "CU", country: "Cuba", code: "53" },
    { id: "CW", country: "Curacao", code: "599" },
    { id: "CY", country: "Cyprus", code: "357" },
    { id: "CZ", country: "Czech Republic", code: "420" },
    { id: "DK", country: "Denmark", code: "45" },
    { id: "DJ", country: "Djibouti", code: "253" },
    { id: "DM", country: "Dominica", code: "1-767" },
    { id: "DO", country: "Dominican Republic", code: "1-809" },
    { id: "EC", country: "Ecuador", code: "593" },
    { id: "EG", country: "Egypt", code: "20" },
    { id: "SV", country: "El Salvador", code: "503" },
    { id: "GQ", country: "Equatorial Guinea", code: "240" },
    { id: "ER", country: "Eritrea", code: "291" },
    { id: "EE", country: "Estonia", code: "372" },
    { id: "ET", country: "Ethiopia", code: "251" },
    { id: "FK", country: "Falkland Islands (Malvinas)", code: "500" },
    { id: "FO", country: "Faroe Islands", code: "298" },
    { id: "FJ", country: "Fiji", code: "679" },
    { id: "FI", country: "Finland", code: "358" },
    { id: "FR", country: "France", code: "33" },
    { id: "GF", country: "French Guiana", code: "594" },
    { id: "PF", country: "French Polynesia", code: "689" },
    { id: "GA", country: "Gabon", code: "241" },
    { id: "GM", country: "Gambia", code: "220" },
    { id: "GE", country: "Georgia", code: "995" },
    { id: "DE", country: "Germany", code: "49" },
    { id: "GH", country: "Ghana", code: "233" },
    { id: "GI", country: "Gibraltar", code: "350" },
    { id: "GR", country: "Greece", code: "30" },
    { id: "GL", country: "Greenland", code: "299" },
    { id: "GD", country: "Grenada", code: "1-473" },
    { id: "GP", country: "Guadeloupe", code: "590" },
    { id: "GU", country: "Guam", code: "1-671" },
    { id: "GT", country: "Guatemala", code: "502" },
    { id: "GG", country: "Guernsey", code: "44" },
    { id: "GN", country: "Guinea", code: "224" },
    { id: "GW", country: "Guinea-Bissau", code: "245" },
    { id: "GY", country: "Guyana", code: "592" },
    { id: "HT", country: "Haiti", code: "509" },
    { id: "HM", country: "Heard Island and McDonald Islands", code: "672" },
    { id: "VA", country: "Holy See (Vatican City State)", code: "379" },
    { id: "HN", country: "Honduras", code: "504" },
    { id: "HK", country: "Hong Kong", code: "852" },
    { id: "HU", country: "Hungary", code: "36" },
    { id: "IS", country: "Iceland", code: "354" },
    { id: "IN", country: "India", code: "91" },
    { id: "ID", country: "Indonesia", code: "62" },
    { id: "IR", country: "Iran, Islamic Republic of", code: "98" },
    { id: "IQ", country: "Iraq", code: "964" },
    { id: "IE", country: "Ireland", code: "353" },
    { id: "IM", country: "Isle of Man", code: "44" },
    { id: "IL", country: "Israel", code: "972" },
    { id: "IT", country: "Italy", code: "39" },
    { id: "JM", country: "Jamaica", code: "1-876" },
    { id: "JP", country: "Japan", code: "81" },
    { id: "JE", country: "Jersey", code: "44" },
    { id: "JO", country: "Jordan", code: "962" },
    { id: "KZ", country: "Kazakhstan", code: "7" },
    { id: "KE", country: "Kenya", code: "254" },
    { id: "KI", country: "Kiribati", code: "686" },
    { id: "KP", country: "Korea, Democratic People's Republic of", code: "850" },
    { id: "KR", country: "Korea, Republic of", code: "82" },
    { id: "KW", country: "Kuwait", code: "965" },
    { id: "KG", country: "Kyrgyzstan", code: "996" },
    { id: "LA", country: "Lao People's Democratic Republic", code: "856" },
    { id: "LV", country: "Latvia", code: "371" },
    { id: "LB", country: "Lebanon", code: "961" },
    { id: "LS", country: "Lesotho", code: "266" },
    { id: "LR", country: "Liberia", code: "231" },
    { id: "LY", country: "Libyan Arab Jamahiriya", code: "218" },
    { id: "LI", country: "Liechtenstein", code: "423" },
    { id: "LT", country: "Lithuania", code: "370" },
    { id: "LU", country: "Luxembourg", code: "352" },
    { id: "MO", country: "Macao", code: "853" },
    {
        id: "MK",
        country: "Macedonia, the former Yugoslav Republic of",
        code: "389",
    },
    { id: "MG", country: "Madagascar", code: "261" },
    { id: "MW", country: "Malawi", code: "265" },
    { id: "MY", country: "Malaysia", code: "60" },

    { ID: "KP", Country: "Korea, Democratic People's Republic of", Code: "850" },
    { ID: "KR", Country: "Korea, Republic of", Code: "82" },
    { ID: "KW", Country: "Kuwait", Code: "965" },
    { ID: "KG", Country: "Kyrgyzstan", Code: "996" },
    { ID: "LA", Country: "Lao People's Democratic Republic", Code: "856" },
    { ID: "LV", Country: "Latvia", Code: "371" },
    { ID: "LB", Country: "Lebanon", Code: "961" },
    { ID: "LS", Country: "Lesotho", Code: "266" },
    { ID: "LR", Country: "Liberia", Code: "231" },
    { ID: "LY", Country: "Libyan Arab Jamahiriya", Code: "218" },
    { ID: "LI", Country: "Liechtenstein", Code: "423" },
    { ID: "LT", Country: "Lithuania", Code: "370" },
    { ID: "LU", Country: "Luxembourg", Code: "352" },
    { ID: "MO", Country: "Macao", Code: "853" },
    {
        ID: "MK",
        Country: "Macedonia, the former Yugoslav Republic of",
        Code: "389",
    },
    { ID: "MG", Country: "Madagascar", Code: "261" },
    { ID: "MW", Country: "Malawi", Code: "265" },
    { ID: "MY", Country: "Malaysia", Code: "60" },
    { ID: "MV", Country: "Maldives", Code: "960" },
    { ID: "ML", Country: "Mali", Code: "223" },
    { ID: "MT", Country: "Malta", Code: "356" },
    { ID: "MH", Country: "Marshall Islands", Code: "692" },
    { ID: "MQ", Country: "Martinique", Code: "596" },
    { ID: "MR", Country: "Mauritania", Code: "222" },
    { ID: "MU", Country: "Mauritius", Code: "230" },
    { ID: "YT", Country: "Mayotte", Code: "262" },
    { ID: "MX", Country: "Mexico", Code: "52" },
    { ID: "FM", Country: "Micronesia, Federated States of", Code: "691" },
    { ID: "MD", Country: "Moldova, Republic of", Code: "373" },
    { ID: "MC", Country: "Monaco", Code: "377" },
    { ID: "MN", Country: "Mongolia", Code: "976" },
    { ID: "ME", Country: "Montenegro", Code: "382" },
    { ID: "MS", Country: "Montserrat", Code: "1-664" },
    { ID: "MA", Country: "Morocco", Code: "212" },
    { ID: "MZ", Country: "Mozambique", Code: "258" },
    { ID: "MM", Country: "Myanmar", Code: "95" },
    { ID: "NA", Country: "Namibia", Code: "264" },
    { ID: "NR", Country: "Nauru", Code: "674" },
    { ID: "NP", Country: "Nepal", Code: "977" },
    { ID: "NL", Country: "Netherlands", Code: "31" },
    { ID: "NC", Country: "New Caledonia", Code: "687" },
    { ID: "NZ", Country: "New Zealand", Code: "64" },
    { ID: "NI", Country: "Nicaragua", Code: "505" },
    { ID: "NE", Country: "Niger", Code: "227" },
    { ID: "NG", Country: "Nigeria", Code: "234" },
    { ID: "NU", Country: "Niue", Code: "683" },
    { ID: "NF", Country: "Norfolk Island", Code: "672" },
    { ID: "MP", Country: "Northern Mariana Islands", Code: "1-670" },
    { ID: "NO", Country: "Norway", Code: "47" },
    { ID: "OM", Country: "Oman", Code: "968" },
    { ID: "PK", Country: "Pakistan", Code: "92" },
    { ID: "PW", Country: "Palau", Code: "680" },
    { ID: "PS", Country: "Palestinian Territory, Occupied", Code: "970" },
    { ID: "PA", Country: "Panama", Code: "507" },
    { ID: "PG", Country: "Papua New Guinea", Code: "675" },
    { ID: "PY", Country: "Paraguay", Code: "595" },
    { ID: "PE", Country: "Peru", Code: "51" },
    { ID: "PH", Country: "Philippines", Code: "63" },
    { ID: "PN", Country: "Pitcairn", Code: "872" },
    { ID: "PL", Country: "Poland", Code: "48" },
    { ID: "PT", Country: "Portugal", Code: "351" },
    { ID: "PR", Country: "Puerto Rico", Code: "1-787 and 1-939" },
    { ID: "QA", Country: "Qatar", Code: "974" },
    { ID: "RE", Country: "Reunion", Code: "262" },
    { ID: "RO", Country: "Romania", Code: "40" },
    { ID: "RU", Country: "Russian Federation", Code: "7" },
    { ID: "RW", Country: "Rwanda", Code: "250" },
    { ID: "BL", Country: "Saint Barthelemy", Code: "590" },
    {
        ID: "SH",
        Country: "Saint Helena, Ascension and Tristan da Cunha",
        Code: "290",
    },
    { ID: "KN", Country: "Saint Kitts and Nevis", Code: "1-869" },
    { ID: "LC", Country: "Saint Lucia", Code: "1-758" },
    { ID: "MF", Country: "Saint Martin (French part)", Code: "590" },
    { ID: "PM", Country: "Saint Pierre and Miquelon", Code: "508" },
    { ID: "VC", Country: "Saint Vincent and the Grenadines", Code: "1-784" },
    { ID: "SM", Country: "San Marino", Code: "378" },
    { ID: "ST", Country: "Sao Tome and Principe", Code: "239" },
    { ID: "SA", Country: "Saudi Arabia", Code: "966" },
    { ID: "SN", Country: "Senegal", Code: "221" },
    { ID: "RS", Country: "Serbia", Code: "381" },
    { ID: "SC", Country: "Seychelles", Code: "248" },
    { ID: "SL", Country: "Sierra Leone", Code: "232" },
    { ID: "SG", Country: "Singapore", Code: "65" },
    { ID: "SX", Country: "Sint Maarten (Dutch part)", Code: "1-721" },
    { ID: "SK", Country: "Slovakia", Code: "421" },
    { ID: "SI", Country: "Slovenia", Code: "386" },
    { ID: "SB", Country: "Solomon Islands", Code: "677" },
    { ID: "SO", Country: "Somalia", Code: "252" },
    { ID: "ZA", Country: "South Africa", Code: "27" },
    {
        ID: "GS",
        Country: "South Georgia and the South Sandwich Islands",
        Code: "500",
    },
    { ID: "ES", Country: "Spain", Code: "34" },
    { ID: "LK", Country: "Sri Lanka", Code: "94" },
    { ID: "SD", Country: "Sudan", Code: "249" },
    { ID: "SR", Country: "Suriname", Code: "597" },
    { ID: "SJ", Country: "Svalbard and Jan Mayen", Code: "47" },
    { ID: "SZ", Country: "Swaziland", Code: "268" },
    { ID: "SE", Country: "Sweden", Code: "46" },
    { ID: "CH", Country: "Switzerland", Code: "41" },
    { ID: "SY", Country: "Syrian Arab Republic", Code: "963" },
    { ID: "TW", Country: "Taiwan, Province of China", Code: "886" },
    { ID: "TJ", Country: "Tajikistan", Code: "992" },
];
